In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!ls

sample_data  survey.txt


In [ ]:
import numpy as np

In [ ]:
a = [ 1, 2, 3, 4]

In [ ]:
for i in a:
  print(i**2)

1
4
9
16


In [ ]:
b = [i**2 for i in a]

In [ ]:
b

[1, 4, 9, 16]

In [ ]:
np_a = np.array(a)

In [ ]:
np_a

array([1, 2, 3, 4])

In [ ]:
a

[1, 2, 3, 4]

In [ ]:
type(a)

list

In [ ]:
type(np_a)

numpy.ndarray

In [ ]:
np_a.shape

(4,)

In [ ]:
np_a.ndim

1

In [ ]:
np_a**2

array([ 1,  4,  9, 16])

In [ ]:
l = range(10000000)

In [ ]:
%timeit [i**2 for i in l]

3.73 s ± 658 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
np_l=np.array(l)

In [ ]:
%timeit np_l**2

36.4 ms ± 573 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
twod_np=np.array([ [1,2,3] , [4,5,6] ])

In [ ]:
twod_np.shape

(2, 3)

In [ ]:
twod_np

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(twod_np)

numpy.ndarray

In [ ]:
np.array([[1,2,4],[3,4,5]])

array([[1, 2, 4],
       [3, 4, 5]])

In [ ]:
np.array([1.2, 3.4, "23"], dtype="int")

array([ 1,  3, 23])

In [ ]:
a=np.array([1,2,3,4] ) # array creation

In [ ]:
a.astype(float) # function calling

array([1., 2., 3., 4.])

In [ ]:
m1 = np.arange(12)

In [ ]:
l = range( 0, 12, 2.5)
[i for i in l]

TypeError: ignored

In [ ]:
l = np.arange( 0, 12, 0.33)
l

array([ 0.  ,  0.33,  0.66,  0.99,  1.32,  1.65,  1.98,  2.31,  2.64,
        2.97,  3.3 ,  3.63,  3.96,  4.29,  4.62,  4.95,  5.28,  5.61,
        5.94,  6.27,  6.6 ,  6.93,  7.26,  7.59,  7.92,  8.25,  8.58,
        8.91,  9.24,  9.57,  9.9 , 10.23, 10.56, 10.89, 11.22, 11.55,
       11.88])

In [ ]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[0]

0

In [ ]:
m1[-2] # single index operation

10

In [ ]:
m1[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
m1[[0, 2]] # multi index operation

array([100, 400])

In [ ]:
m1[[0, 5, 4, 7, 9, 2]]

array([0, 5, 4, 7, 9, 2])

In [ ]:
m1 = np.array([100, 200, 400, 500, 700])

In [ ]:
m1[[0, 4, 2]]

array([100, 700, 400])

In [ ]:
m1[[0, 0, 2]]

array([100, 100, 400])

In [ ]:
m1

array([100, 200, 400, 500, 700])

In [ ]:
m1[0:3]

array([100, 200, 400])

In [ ]:
m1[-3:-1]

array([400, 500])

In [ ]:
m1 = np.array([0, 0 , 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1 <= 6

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False])

In [ ]:
m1 [[ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False]]

array([0, 0, 1, 2, 3])

In [ ]:
m1 [ m1 < 4 ]

array([0, 0, 1, 2, 3])

In [ ]:
m1

array([ 0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m1%2==0

array([ True,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [ ]:
m1 [ m1%2==0 ]

array([ 0,  0,  2,  4,  6,  8, 10])

In [ ]:
m1 [ m1%2==1 ]

array([1, 3, 5, 7, 9])

In [ ]:
m1 = np.array([ 100 , 200, 300])

In [ ]:
m1[ m1<=100 ]

array([100])

# NPS

In [ ]:
score  = np.loadtxt( "survey.txt", dtype="int")

In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
type(score)

numpy.ndarray

In [ ]:
score[1]

10

In [ ]:
score.shape

(1167,)

In [ ]:
score.ndim

1

In [ ]:
# NPS = % promotors - % detractors

In [ ]:
score<=6

array([False, False,  True, ...,  True, False, False])

In [ ]:
detractors = score[ score<=6 ]

In [ ]:
detractors.shape

(332,)

In [ ]:
promotors = score[ score>=9 ]

In [ ]:
promotors.shape

(609,)

In [ ]:
num_promotors = len(promotors)

In [ ]:
num_detractors = len(detractors)

In [ ]:
total = len(score)

In [ ]:
percentage_promotors = (num_promotors/total)

In [ ]:
percentage_detractors = (num_detractors/total)

In [ ]:
percentage_promotors

0.5218508997429306

In [ ]:
percentage_detractors

0.28449014567266495

In [ ]:
nps = percentage_promotors - percentage_detractors

In [ ]:
round(nps*100,2)

23.74

In [ ]:
score.min()

1

In [ ]:
score.max()

10

In [ ]:
score.mean()

7.250214224507284

In [ ]:
7, 8

-1